language: cpp
cache:
    - ccache
    - directories:
        - ~/.ethash
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          env: TRAVIS_BUILD_TYPE=Debug
        - os: osx
          osx_image: xcode7.3
          env: TRAVIS_BUILD_TYPE=Debug
git:
    depth: 2
branches:
    # Build only pushes to main branches to avoid double builds of internal PRs.
    only:
        - master
        - develop
before_install: ./install_dependencies.sh
script:
    - ./fetch_umbrella_build.sh
    - ./libethereum/test/testeth --verbosity 2
